import type { Metadata } from "next";
import "./globals.css";
import LayoutPage from "@/components/Layout/Layout";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
  keywords: "Next.js, React, TypeScript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="sq">
      <body>

        <LayoutPage>
        {children}
        </LayoutPage>

      </body>
    </html>
  );
}
